# Generated by Django 5.2.3 on 2025-07-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_baseuser_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="location",
            field=models.CharField(
                default="Russia", max_length=50, verbose_name="Страна проживания"
            ),
        ),
    ]
