# Generated by Django 5.2.3 on 2025-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_baseuser_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="users/", verbose_name="Фотография"
            ),
        ),
    ]
