# Generated by Django 5.2.1 on 2025-06-12 17:08

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        null=True,
                        upload_to=pathlib.PureWindowsPath(
                            "C:/Users/Maxim-NOTE/Documents/Skypro/22_Django/media"
                        ),
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "publication_flag",
                    models.BooleanField(
                        default=False, help_text="Признак", verbose_name="Признак"
                    ),
                ),
                (
                    "number_views",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title"],
            },
        ),
    ]
