# Generated by Django 5.2.1 on 2025-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="preview",
            field=models.ImageField(
                null=True,
                upload_to="blog:C:\\Users\\Maxim-NOTE\\Documents\\Skypro\\22_Django\\media",
                verbose_name="Фотография",
            ),
        ),
    ]
