# Generated by Django 5.2.3 on 2025-08-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={
                "ordering": ["title"],
                "permissions": [("add_comments", "You can leave a comment")],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
