# Generated by Django 5.2.4 on 2025-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_posts_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="posts/", verbose_name="Фотография"
            ),
        ),
    ]
