# Generated by Django 5.2.1 on 2025-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_posts_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/", verbose_name="Фотография"
            ),
        ),
    ]
