# Generated by Django 5.2.3 on 2025-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_posts_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="publication_flag",
            field=models.BooleanField(default=False, help_text="Признак"),
        ),
    ]
