# Generated by Django 5.2.1 on 2025-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_posts_number_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="number_views",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
