# Generated by Django 5.2.3 on 2025-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_posts_publication_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="publication_flag",
            field=models.BooleanField(default=False, verbose_name="Видно всем?"),
        ),
    ]
