# Generated by Django 5.2.1 on 2025-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Имя"),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="photos/", verbose_name="Фотография"
                    ),
                ),
                ("birthday", models.DateTimeField(verbose_name="День рождения")),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name"],
            },
        ),
    ]
