# Generated by Django 5.2.3 on 2025-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_on_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=True),
        ),
    ]
