# Generated by Django 5.2.1 on 2025-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={
                "ordering": ["name"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="users",
            name="surname",
            field=models.CharField(max_length=200, verbose_name="Фамилия"),
        ),
    ]
